In [ ]:
import numpy as np
import matplotlib.pyplot as plt 
# axis =0 top to bottom column
# axis =1 left to right

# sales_data[:,1:] : first reperenst row ,second represent column 

# data structure : [resturant_id ,2021,2022,2023,2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("zomoto sales analysis===")
print("sales data shape ",sales_data.shape)

# question print first 3 resturant data
print("first three" ,sales_data[:3])

print("data",sales_data[:,1:])

print("total sales per year",np.sum(sales_data,axis=0))
print("total sales per year",np.sum(sales_data[:,1:],axis=0))



#minimim sales per resturant 
min_sales = np.min(sales_data[ : ,1: ] ,axis=1)
print(min_sales)

print(np.argmin(min_sales))


# maximum sales_data
max_sales = np.max(sales_data[ : ,1: ] ,axis=1)
print(max_sales)
print(np.argmax(min_sales))


# find max sale of 2021
print(np.argmax(sales_data[:,1:],axis=0))

#average sales per resturant
# 
print("average", np.mean(sales_data[:,1:],axis=1))







zomoto sales analysis===
sales data shape  (5, 5)
first three [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
data [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
total sales per year [     15  810000  945000 1085000 1240000]
total sales per year [ 810000  945000 1085000 1240000]
[150000 120000 200000 180000 160000]
1
[250000 190000 300000 270000 230000]
2
[2 2 2 2]
average [200000. 152500. 247500. 225000. 195000.]
