In [ ]:
import numpy as np
print("hello")
arr= np.array([1,2,3,4,5,6,7,8,9])

# Slicing ---------------------------------------------
print("basic slicing", arr[4:10])
# every second postion
print("every second postion slicing", arr[4:10:2])
# negative indexing : it start from -1 from end
print(" negative indexing", arr[-1])

# Note : array[row_slice, column_slice]



#2d array 
array2_d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element ",array2_d[2,2])
print("entire row ",array2_d[1])
print("entire column ",array2_d[:,2])



#sorting ---------------------------------------------
unsorted =np.array([1,2,39,8,7,5,4,0])
print("sotrted array ",np.sort(unsorted))

#2d sorting
# axis=0: Sorts along columns (vertically ↓).
# axis=1: Would sort along rows (horizontally →) .

arr_2_d_unsorted =np.array([[3,1],[2,3],[1,2]])
print("sorted 2d array unsorted array",np.sort(arr_2_d_unsorted,axis=0))


#filter ---------------------------------------------
numbers= np.array([1,2,3,4,5,6,7,8,9])
# numpy  allow to write the experssion also inplace  of index 
even_number=numbers[numbers %2 == 0]
print("eveen number",even_number)


#filter with mask  ---------------------------------------------
# masking allows you to filter elements of an array based on a condition. A mask is a boolean array where True indicates that the corresponding element of the array should be selected.

mask= (numbers >5) & (numbers<9)
print("mask example : ",numbers[mask])


#fancy indexing  ---------------------------------------------
indices =[0,2,4]
print(numbers[indices])
where_result =np.where(numbers>5)
print(where_result) 
# where_result : contain the indexes
print("NP where ",numbers[where_result])

condition_array =np.where(numbers>5, numbers*5,numbers)
print(condition_array)


#adding and removing data  ---------------------------------------------
arr1 =np.array([1,2,3])
arr2 =np.array([11,12,13,6])


combined =np.concatenate((arr1,arr2))
print("combined array",combined)

# shape compatability
print("shape compatability ",arr1.shape==arr2.shape)

original=np.array([[1,2],[3,4]])
new_row =np.array([5,6])

with_new_row=np.vstack([original,new_row])
# vstack add the row 
print("with new row ",with_new_row)

# hstack add the column 
new_col=np.array([[7],[6]])
with_new_col =np.hstack((original,new_col))
print("with new col",with_new_col)

#removing

arr=np.array([1,2,3,4,5,6,7,8,9])
deleted = np.delete(arr,4)
# it return the deleted value 
print("deleted ",deleted)






              

hello
basic slicing [5 6 7 8 9]
every second postion slicing [5 7 9]
 negative indexing 9
specific element  9
entire row  [4 5 6]
entire column  [3 6 9]
sotrted array  [ 0  1  2  4  5  7  8 39]
sorted 2d array unsorted array [[1 1]
 [2 2]
 [3 3]]
eveen number [2 4 6 8]
mask example :  [6 7 8]
[1 3 5]
(array([5, 6, 7, 8]),)
NP where  [6 7 8 9]
[ 1  2  3  4  5 30 35 40 45]
combined array [ 1  2  3 11 12 13  6]
shape compatability  False
with new row  [[1 2]
 [3 4]
 [5 6]]
with new col [[1 2 7]
 [3 4 6]]
deleted  [1 2 3 4 6 7 8 9]
arr [1 2 3 4 5 6 7 8 9]
