In [35]:
import numpy as np
### one d array
arr1=np.array([1,2,3])
print(arr1)
### two d array
arry2=np.array([[1,3,5],[6,7,8]])
print(arry2)

[1 2 3]
[[1 3 5]
 [6 7 8]]


In [36]:
# zeores
arr1=np.zeros((2,3))
print("arr1",arr1)

arr1 [[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
# Ones
arr1=np.ones((2,3))
print("arr1",arr1)


arr1 [[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
# full
arr1=np.full((2,3),5)
print(arr1)



[[5 5 5]
 [5 5 5]]


In [41]:
# Random
random=np.random.random((2,3))
print(random)

#sequence
seq=np.arange(1,10,2)
print("seq",seq)


[[0.8946162  0.73039095 0.50919792]
 [0.40396457 0.2792065  0.58627278]]
seq [1 3 5 7 9]


In [45]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)



shape (2, 3)
Dimension 2
size 6
Dtype int64


In [55]:
#Reshaping
arr1=np.arange(15)
print(arr1)
arr1=arr1.reshape((3,5))
print(arr1)

#flatten
arr1=arr1.flatten()
print(arr1)

#ravel
raveld=arr1.ravel()
print("raveld",raveld)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
raveld [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
import numpy as np
#Transpose
arr1=np.arange(15)
print(arr1)
arr1=arr1.reshape((3,5))
print(arr1)
arr1=arr1.T
print(arr1)


# Sum 
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  
    [2, 120000, 140000, 160000, 190000],  
    [3, 200000, 230000, 260000, 300000],
    [4, 180000, 210000, 240000, 270000],
    [5, 160000, 185000, 205000, 230000]  
])
print(np.sum(sales_data,axis=0))

# axis =0 : sum column row wise
# axis =1 : sum row wise 


#max & min 
arr=np.array([100, 0 , 1 , 2,  3 , 4,  5  ,6  ,7 , 8  ,9 ,10, 11 ,12 ,13, 14])
print(np.min(arr))
#it print the index also 
print(np.argmin(arr)) 
print(np.max(arr))
#it print the index also 
print(np.argmax(arr)) 




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[     15  810000  945000 1085000 1240000]
0
1
100
0
