<a href="https://colab.research.google.com/github/aamitRai/AI_ML_learning/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
print(torch.__version__)



2.6.0+cu124


In [5]:
if torch.cuda.is_available():
  print("GPU is available")
else :
    print("GPU is not available")

GPU is available


In [14]:
#using empty
a=torch.empty(2,3)



In [15]:

#Check Type
type(a)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
#using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
# using rand
torch.rand(2,3)

tensor([[0.2553, 0.3075, 0.4713],
        [0.0679, 0.5709, 0.3479]])

In [19]:
# use of seed
torch.rand(2,3)

tensor([[0.4418, 0.8339, 0.8941],
        [0.5745, 0.9408, 0.6948]])

In [20]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [3]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [4]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
# arange
print("using arange ->", torch.arange(0,10,2))  # Creates a 1D tensor with values from 0 to 10 (exclusive) in steps of 2.

# linspace
print("using linspace ->", torch.linspace(0,10,10))  # Creates a 1D tensor with 10 evenly spaced values from 0 to 10.

# eye
print("using eye ->", torch.eye(5))  # Creates a 5x5 identity matrix (ones on the diagonal, zeros elsewhere).

# full
print("using full ->", torch.full((4, 4), 5))  # Creates a 4x4 tensor filled with the value 5.



using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [11]:
# Tensor Shape
x= torch.tensor([[1,2],[3,4]])
x.shape

torch.Size([2, 2])

In [12]:
torch.empty_like(x)


tensor([[7309453675965983778, 8315168162784306286],
        [8367752027310484831, 7954801838398993778]])

In [13]:
torch.zeros_like(x)


tensor([[0, 0],
        [0, 0]])

In [14]:
torch.ones_like(x)


tensor([[1, 1],
        [1, 1]])

In [15]:
torch.rand_like(x, dtype=torch.float32)


tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [16]:
# Data Type

In [19]:
x.dtype



torch.int64

In [20]:
# using to()
x.to(torch.float32)


tensor([[1., 2.],
        [3., 4.]])

In [22]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

Data Type	Dtype	Description
32-bit Floating Point	torch.float32	Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.
64-bit Floating Point	torch.float64	Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.
16-bit Floating Point	torch.float16	Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.
BFloat16	torch.bfloat16	Brain floating-point format with reduced precision compared to float16. Used in mixed-precision training, especially on TPUs.
8-bit Floating Point	torch.float8	Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).
8-bit Integer	torch.int8	8-bit signed integer. Used for quantized models to save memory and computation in inference.
16-bit Integer	torch.int16	16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.
32-bit Integer	torch.int32	Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.
64-bit Integer	torch.int64	Long integer type. Often used for large indexing arrays or for tasks involving large numbers.
8-bit Unsigned Integer	torch.uint8	8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).
Boolean	torch.bool	Boolean type, stores True or False values. Often used for masks in logical operations.
Complex 64	torch.complex64	Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.
Complex 128	torch.complex128	Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.
Quantized Integer	torch.qint8	Quantized signed 8-bit integer. Used in quantized models for efficient inference.
Quantized Unsigned Integer	torch.quint8	Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.

SyntaxError: invalid syntax (ipython-input-23-3373058891.py, line 1)

In [24]:
# Mathematical operations

In [25]:
# 1. Scalar operation

In [26]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[ 1,  4],
        [ 9, 16]])

In [27]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [29]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [41]:
c = torch.tensor([1, -2, 3, -4])
# abs
torch.abs(c)
# negative
torch.neg(c)


tensor([-1,  2, -3,  4])

In [46]:
d = torch.tensor([1.9, 2.6, 3.7, 4.4])
# round
# torch.round(d)

In [47]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [48]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [49]:
# clamp : it make below 2 to 2 and above 3 to 3
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.6000, 3.0000, 3.0000])

In [ ]:
# 3. Reduction operation

In [60]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e


In [56]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)
e



tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [59]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)
e


tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [61]:
# median
torch.median(e)

tensor(4.)

In [62]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [63]:
# product
torch.prod(e)

tensor(0.)

In [64]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [65]:
# variance
torch.var(e)


tensor(9.8667)

In [66]:
# argmax
torch.argmax(e)


tensor(3)

In [67]:
# argmin
torch.argmin(e)

tensor(5)

4. Matrix operations

In [68]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [69]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [70]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [71]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [74]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [78]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
# determinant
torch.det(h)


tensor([[ 0.8000,  0.6000, -1.6000],
        [ 0.4500,  0.6500, -1.4000],
        [-0.7500, -0.7500,  2.0000]])

In [79]:
# inverse
torch.inverse(h)

tensor([[ 0.8000,  0.6000, -1.6000],
        [ 0.4500,  0.6500, -1.4000],
        [-0.7500, -0.7500,  2.0000]])

5. Comparison operations

In [80]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 6, 4],
        [0, 8, 4]])
tensor([[7, 2, 3],
        [8, 5, 6]])


In [81]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to


tensor([[True, True, True],
        [True, True, True]])

6. Special functions

In [82]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 9., 5.],
        [0., 4., 2.]])

In [83]:
# log
torch.log(k)

tensor([[0.6931, 2.1972, 1.6094],
        [  -inf, 1.3863, 0.6931]])

In [84]:
#exp
torch.exp(k)

tensor([[7.3891e+00, 8.1031e+03, 1.4841e+02],
        [1.0000e+00, 5.4598e+01, 7.3891e+00]])

In [85]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 3.0000, 2.2361],
        [0.0000, 2.0000, 1.4142]])

In [86]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9999, 0.9933],
        [0.5000, 0.9820, 0.8808]])

In [87]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.9933, 0.9526],
        [0.1192, 0.0067, 0.0474]])

In [88]:
# relu
torch.relu(k)

tensor([[2., 9., 5.],
        [0., 4., 2.]])

Inplace Operations

In [90]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])
tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])


In [91]:
m.add_(n)

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [92]:
m


tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [93]:
torch.relu(m)

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [94]:
m.relu_()
m


tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

# Copying the Tensor

In [95]:
a = torch.rand(2,3)
a

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [96]:
b = a

In [97]:
b

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [98]:
a[0][0] = 0

In [99]:
a


tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [100]:
b

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [101]:
id(a)

137268031798928

In [102]:
id(b)

137268031798928

In [130]:
b = a.clone()

In [131]:
b



tensor([[3.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [132]:
a[0][0] = 9

In [133]:
a

tensor([[9.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [134]:
b

tensor([[3.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])